<a href="https://colab.research.google.com/github/zaedulislam/Deep_Learning_A-Z_Hands-On_Artificial_Neural_Networks/blob/main/Deep_Learning_A-Z_Hands-On_Artificial_Neural_Networks/Section%204%20-%20Building%20an%20ANN/Building%20an%20ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network

### Importing the libraries

In [18]:
import numpy as np
import pandas as pd
# TensorFlow is already preinstalled as a library in Google Colab, but we still need to import it
import tensorflow as tf

In [19]:
# Check the tensorflow version
tf.__version__

'2.6.0'

# Part 1 - Data Processing

### Importing the dataset

In [20]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
# Create matrix of Feature
# Take all the columns starting from colum #3(CreditScore) to column #9(EstimatedSalary), finishing 1 before last column
X = dataset.iloc[:, 3:-1].values
# Take only the last column of the dataset
y = dataset.iloc[:, -1].values

In [21]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [22]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding categorical data

### Label Encoding the "Gender" column

In [24]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
X[:, 2] = labelEncoder.fit_transform(X[:, 2])

In [25]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Note: "Female" is encoded to "0", "Male" is to "1". That's, of course, a random decision of the machine to choose this Integers, associations.

### One Hot Encoding the "Geography" column

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
columnTransformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(columnTransformer.fit_transform(X))

In [30]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Note: When we perform one hot coding while the dummy variables are actually moved to the first columns of the Matrix features in the three first columns.

"1.0 0.0 0.0", this is the first combination of dummy variables which corresponds to France. Now, Spain was encoded into "0.0 0.0 1.0". And finally, Germany was encoded into "1.0 0.0 0.0".

### Splitting the dataset into the Training set and Test set

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [34]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
X_train = standardScaler.fit_transform(X_train)
X_test = standardScaler.transform(X_test)