<a href="https://colab.research.google.com/github/zaedulislam/Deep_Learning_A-Z_Hands-On_Artificial_Neural_Networks/blob/main/Section%204%20-%20Building%20an%20ANN/Artificial%20Neural%20Network%20(ANN).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Artificial Neural Network (ANN)

Notion Page: https://www.notion.so/zaedulislam/Deep-Learning-A-Z-Hands-On-Artificial-Neural-Networks-b0f4742181e74b8da987a0db61e0ced9#1d902de55d07493c884942a0ce49c349

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
# TensorFlow is already preinstalled as a library in Google Colab, but we still need to import it
import tensorflow as tf

In [ ]:
# Check the tensorflow version
tf.__version__

'2.6.0'

## Part 1 - Data Processing

### Importing the dataset

In [ ]:
dataset = pd.read_csv('/content/Churn_Modelling.csv')
# Create matrix of Feature
# Take all the columns starting from colum #3(CreditScore) to column #9(EstimatedSalary), finishing 1 before last column
X = dataset.iloc[:, 3:-1].values
# Take only the last column of the dataset
y = dataset.iloc[:, -1].values

In [ ]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [ ]:
print(y)

[1 0 1 ... 1 1 0]


## Encoding categorical data

### Label Encoding the "Gender" column

In [ ]:
from sklearn.preprocessing import LabelEncoder
labelEncoder = LabelEncoder()
X[:, 2] = labelEncoder.fit_transform(X[:, 2])

In [ ]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


Note: "Female" is encoded to "0", "Male" is to "1". That's, of course, a random decision of the machine to choose this Integers, associations.

### One Hot Encoding the "Geography" column

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
columnTransformer = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(columnTransformer.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


Note: When we perform one hot coding while the dummy variables are actually moved to the first columns of the Matrix features in the three first columns.

"1.0 0.0 0.0", this is the first combination of dummy variables which corresponds to France. Now, Spain was encoded into "0.0 0.0 1.0". And finally, Germany was encoded into "1.0 0.0 0.0".

### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()
X_train = standardScaler.fit_transform(X_train)
X_test = standardScaler.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
# Creates ANN variable, that represents the artificial neural network, created as an instance of that sequential class which initializes or artificial neural network 
# as a sequence of layers 
# Sequential class taken from the "models" module, from the "Keras" library, which since tensorflow 2.0 belongs to the tensorflow
ann = tf.keras.models.Sequential()

### Adding the input later and the first hidden layer

In [ ]:
# Add the input layer and the first hidden layer composed of a certain number of neurons
# "Dense" class in Tensorflow and pyTorch, which is another great library to build new networks
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
# Add the second hidden layer, in order to build indeed a deep learning model as opposed to a shallow learning model
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer= 'adam', loss= 'binary_crossentropy', metrics= ['accuracy'])

### Training the ANN on the Training set

In [ ]:
ann.fit(x= X_train, y= y_train, batch_size= 32, epochs= 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5366 - accuracy: 0.7638
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4597 - accuracy: 0.7962
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4435 - accuracy: 0.7995
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4344 - accuracy: 0.8034
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4283 - accuracy: 0.8044
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4228 - accuracy: 0.8086
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4155 - accuracy: 0.8114
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4055 - accuracy: 0.8135
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3957 - accuracy: 0.8154
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3875 - accura